set nocompatible

" user commands
command! -nargs=0 -bang WSudo :silent! w !sudo tee % &>/dev/null
command! -nargs=0 Vimrc :tabnew $MYVIMRC

set keymap=russian-jcukenwin " ^6 to change
set iminsert=0 " latin by default
set imsearch=0 " latin by default

" disable mouse
set mouse="

" indentation settings
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set shiftround " remove extra spaces during indentation

set wrap

" search and replace
set ignorecase
set smartcase
set hlsearch

set updatetime=120000
set hidden

" folding settings
set foldlevelstart=20

" move to next line at beginning/line of the current
set whichwrap=h,l,<,>,[,]

" turn off speaker
set vb t_vb="

set wildignore+=*.o,*.bak,*.pyc,*.jpg,*.png,*/.git/*,*/.hg/*,*/.svn/*

augroup misc
    au! BufNewFile,BufRead * setlocal vb t_vb="

    " do not highlight tabs and stuff for taskpaper and golang sources
    au! BufNewFile,BufRead *.taskpaper setlocal nolist
    au! BufNewFile,BufRead *.go setlocal nolist
augroup end

set undolevels=1000
set undoreload=10000
set undodir=~/.vim/undo
set undofile

" store swap files in a separate directory
set directory=~/.vim/swap

" Suffixes that get lower priority when doing tab completion for filenames.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set suffixesadd=.pl,.pm,.yml,.yaml " for `gf' (open file under cursor)

" Complete options (disable preview scratch window)
set completeopt=menu,menuone,longest
" Limit popup menu height
set pumheight=15

set list listchars=tab:>\ ,trail:_,extends:>

set colorcolumn=80,100,120

set viminfo='0,:500,<0,@100,f0

let g:google_machine = isdirectory("/google")

source ~/.vim/plugins.vim

source ~/.vim/backup.vim
source ~/.vim/ftdetect.vim
source ~/.vim/keymap.vim
source ~/.vim/appearance.vim

if g:google_machine
  source ~/.vim/google.vim
endif

runtime! macros/matchit.vim
runtime! indent.vim
runtime! fvl.vim
